=== webasyst/webasyst-framework/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Theme -->
<!ELEMENT theme (name+,description*,instruction*,support*,files*,about*, settings?, thumbs?, locales?, requirements?)>
<!ATTLIST theme
    id CDATA #REQUIRED
    system (1|0) "0"
    vendor CDATA #IMPLIED
    author CDATA #IMPLIED
    app CDATA #REQUIRED
    parent_theme_id CDATA #IMPLIED
    version CDATA #IMPLIED
    edition CDATA #IMPLIED
    source_theme_id CDATA #IMPLIED
    demo (1|0) "0"
>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    locale CDATA #REQUIRED
>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
    locale CDATA #REQUIRED
>

<!ELEMENT instruction (#PCDATA)>
<!ATTLIST instruction
    locale CDATA #REQUIRED
>

<!ELEMENT support (#PCDATA)>
<!ATTLIST support
    locale CDATA #REQUIRED
>

<!-- Theme's files list available for editing -->
<!ELEMENT files (file+)>

<!ELEMENT file (description*)>
<!ATTLIST file
    path CDATA #REQUIRED
    custom (1|0) "0"
    parent (1|0) "0"
    modified (1|0) "0"
>

<!-- Theme usage hints and instructions -->
<!ELEMENT about (#PCDATA)>
<!ATTLIST about
    locale CDATA #REQUIRED
>

<!-- Theme settings -->
<!ELEMENT settings (setting+)>
<!-- Theme setting -->
<!ELEMENT setting (value+,filename?,name+,tooltip*,description*,options?)>
<!ATTLIST setting
    var CDATA #REQUIRED
    control_type (text|select|checkbox|radio|color|color_select|image|image_select|image_width|paragraph|group_divider) "text"
    invisible (true|false) "false"
    icon_class CDATA #IMPLIED
    image CDATA #IMPLIED
    max_width CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
    locale CDATA #IMPLIED
>
<!ELEMENT tooltip (#PCDATA)>
<!ATTLIST tooltip
    locale CDATA #REQUIRED
>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT options (option+)>
<!ELEMENT option (name*,description*)>
<!ATTLIST option
    value CDATA #IMPLIED
>
<!--List of allowed thumb sizes-->
<!ELEMENT thumbs (thumb*)>
<!ELEMENT thumb (#PCDATA)>

<!--Theme strings-->
<!ELEMENT locales (locale+)>
<!ELEMENT locale (msgid,msgstr+)>
<!ELEMENT msgid (#PCDATA)>
<!ELEMENT msgstr (#PCDATA)>
<!ATTLIST msgstr
    locale CDATA #REQUIRED
>

<!--Theme requirements-->
<!ELEMENT requirements (requirement+)>
<!ELEMENT requirement (name*,description*)>
<!ATTLIST requirement
    property CDATA #REQUIRED
    value CDATA #REQUIRED
    strict (true|false) "false"
>

=== webasyst/webasyst-framework/wa-apps/site/themes/sidebar/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="sidebar" system="0" vendor="webasyst" author="Webasyst" app="site" version="2.1.17">
    <name locale="en_US">Sidebar 2.0</name>
    <name locale="ru_RU">Sidebar 2.0</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of the Sidebar theme family</description>
            <description locale="ru_RU">Основной макет тем дизайна семейства Sidebar</description>
        </file>
        <file path="sidebar.css" custom="0">
            <description locale="en_US">Core CSS of the Sidebar theme family</description>
            <description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна Sidebar</description>
        </file>
        <file path="sidebar.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout for the Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">My profile navigation</description>
            <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
        </file>
        <file path="nav.sidebar.html" custom="0">
            <description locale="en_US">Internal app navigation tree</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
<p><b>Sidebar 2.0</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Sidebar (i.e. this) theme for the Site application. All Sidebar design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
<p>Sidebar design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
<p><b>Sidebar 2.0</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Sidebar для приложения «Сайт» (данная тема). Все темы дизайна Sidebar для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Sidebar оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
    <settings>
        <setting var="logo" control_type="image">
            <value></value>
            <filename>img/logo.*</filename>
            <name locale="en_US">Logo</name>
            <name locale="ru_RU">Логотип</name>
        </setting>
        <setting var="sidebar_unfolded_nav" control_type="checkbox">
            <value>1</value>
            <name locale="en_US">Automatically unfold sidebar navigation tree</name>
            <name locale="ru_RU">Автоматически разворачивать дерево навигации в боковой панели</name>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
        <setting var="use_shop_schedule" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать график работы магазина на текущую неделю из настроек Shop-Script</name>
            <name locale="en_US">Show online store’s working schedule for current week from Shop-Script settings</name>
            <description locale="ru_RU">При включении игнорируется настройка «Сокращенный график работы».</description>
            <description locale="en_US">When enabled, “Brief working schedule” setting is ignored.</description>
        </setting>
        <setting var="manual_schedule" control_type="text">
            <value></value>
            <name locale="ru_RU">Сокращенный график работы</name>
            <name locale="en_US">Brief working schedule</name>
            <description locale="ru_RU">Например: Пн—Сб 08:00–18:00</description>
            <description locale="en_US">Example: Mo—Sa 08:00–18:00</description>
        </setting>
    </settings>
</theme>

=== webasyst/webasyst-framework/wa-apps/photos/themes/mobile/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="mobile" system="0" vendor="webasyst" author="Webasyst" app="photos" parent_theme_id="site:mobile" version="1.0.0">
    <name locale="en_US">Mobile</name>
    <name locale="ru_RU">Mobile</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="album.html" custom="0">
            <description locale="en_US">Wrapper for photo album</description>
            <description locale="ru_RU">Обертка для альбома фотографий</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Photos app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Фото»</description>
        </file>
        <file path="home.html" custom="0">
            <description locale="en_US">Wrapper for the main photo gallery homepage</description>
            <description locale="ru_RU">Обертка для главной страницы фотогалереи</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Photos app content</description>
            <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Фото»</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content</description>
            <description locale="ru_RU">Содержимое информационной страницы</description>
        </file>
        <file path="photo.html" custom="0">
            <description locale="en_US">One photo and its details</description>
            <description locale="ru_RU">Просмотр фотографий по одной</description>
        </file>
        <file path="photos-thumbs.html" custom="0">
            <description locale="en_US">Photo list thumbnails view</description>
            <description locale="ru_RU">Список фотографий эскизами</description>
        </file>
        <file path="photos-plain.html" custom="0">
            <description locale="en_US">Photo list plain view</description>
            <description locale="ru_RU">Список фотографий «простыней»</description>
        </file>
        <file path="search.html" custom="0">
            <description locale="en_US">Wrapper for photo search (filtering) results, e.g. by tag or by rating</description>
            <description locale="ru_RU">Обертка для страницы поиска (фильтрации) фотографий, например, по тегу или автору</description>
        </file>

        <file path="mobile.photos.css" custom="0">
        </file>
        <file path="mobile.photos.js" custom="0">
        </file>

        <file path="error.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="index.html" parent="1">
        </file>
        <file path="layout-head.html" parent="1">
        </file>
        <file path="layout-header.html" parent="1">
        </file>
        <file path="layout-menu.html" parent="1">
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="mobile.css" parent="1">
        </file>
        <file path="mobile.js" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
]]>
    </about>
</theme>

=== webasyst/webasyst-framework/wa-apps/site/themes/mobile/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="mobile" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.3.19">
    <name locale="en_US">Mobile</name>
    <name locale="ru_RU">Mobile</name>
    <description locale="en_US">Theme for mobile devices</description>
    <description locale="ru_RU">Тема для мобильных устройств</description>
    <files>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of theme</description>
            <description locale="ru_RU">Индексный шаблон темы</description>
        </file>
        <file path="layout-head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="layout-header.html" custom="0">
            <description locale="en_US">App specific header content</description>
            <description locale="ru_RU">Содержимое «шапки» приложения</description>
        </file>
        <file path="layout-menu.html" custom="0">
            <description locale="en_US">App hidden menu content</description>
            <description locale="ru_RU">Содержимое «скрытого меню» приложения</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout for Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Личный кабинет: редактирование контактной информации</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="mobile.css" custom="0">
            <description locale="en_US">General CSS for Site Application</description>
            <description locale="ru_RU">Основные стили для приложения "Сайт"</description>
        </file>
        <file path="mobile.js" custom="0">
            <description locale="en_US">General JavaScript for Site Application</description>
            <description locale="ru_RU">Основные скрипты для приложения "Сайт"</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
]]>
    </about>
    <settings>
        <setting var="logo" control_type="image">
            <value></value>
            <filename>img/logo.*</filename>
            <name locale="en_US">Slide-out menu logo</name>
            <name locale="ru_RU">Логотип в боковой панели</name>
            <description locale="en_US">PNG with alpha channel. Logo is displayed in the slide-out menu.</description>
            <description locale="ru_RU">PNG с прозрачностью. Логотип отображается в боковой панели.</description>
        </setting>
        <setting var="pagination" control_type="select">
            <value>lazyloading</value>
            <name locale="en_US">Displaying of long product lists</name>
            <name locale="ru_RU">Отображение длинных списков товаров</name>
            <description locale="ru_RU">Применяется к спискам товаров в категориях и результатах поиска.</description>
            <description locale="en_US">For category-listing pages and search results.</description>
            <options>
                <option value="lazyloading">
                    <name locale="ru_RU">Автоматически загружать содержимое при прокручивании страницы</name>
                    <name locale="en_US">Automatically load content on page scrolling</name>
                </option>
                <option value="paging">
                    <name locale="ru_RU">Постраничная навигация (1 2 3 4)</name>
                    <name locale="en_US">Paginated lists (1 2 3 4)</name>
                </option>
            </options>
        </setting>
        <setting var="show_full_site_link" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Отображать ссылку на полную версию сайта</name>
            <name locale="en_US">Display a link to the full version of the site</name>
            <description locale="ru_RU">Ссылку показывается в боковой панели.
            </description>
            <description locale="en_US">The link will be displayed in the bottom of the slide-out menu.
            </description>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
        <setting var="use_shop_schedule" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать график работы магазина на текущую неделю из настроек Shop-Script</name>
            <name locale="en_US">Show online store’s working schedule for current week from Shop-Script settings</name>
            <description locale="ru_RU">При включении игнорируется настройка «Сокращенный график работы».</description>
            <description locale="en_US">When enabled, “Brief working schedule” setting is ignored.</description>
        </setting>
        <setting var="manual_schedule" control_type="text">
            <value></value>
            <name locale="ru_RU">Сокращенный график работы</name>
            <name locale="en_US">Brief working schedule</name>
            <description locale="ru_RU">Например: Пн—Сб 08:00–18:00</description>
            <description locale="en_US">Example: Mo—Sa 08:00–18:00</description>
        </setting>
        <setting var="show_cart" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать корзину покупок</name>
            <name locale="en_US">Show shopping cart</name>
            <description locale="ru_RU">Корзина будет показана, если на сайте настроена хотя бы одна витрина интернет-магазина Shop-Script.</description>
            <description locale="en_US">The shopping cart will be shown if at least one Shop-Script storefront is set up on the website.</description>
        </setting>
    </settings>
    <locales>
        <locale>
            <msgid>Follow us</msgid>
            <msgstr locale="ru_RU">Подписаться на новости</msgstr>
        </locale>
        <locale>
            <msgid>Subscribe to our email newsletter</msgid>
            <msgstr locale="ru_RU">Подписаться на рассылку</msgstr>
        </locale>
        <locale>
            <msgid>Or follow us on Facebook and Twitter</msgid>
            <msgstr locale="ru_RU">Или подписывайтесь в соцсетях</msgstr>
        </locale>
        <locale>
            <msgid>Editors’ choice</msgid>
            <msgstr locale="ru_RU">Избранное</msgstr>
        </locale>
        <locale>
            <msgid>All photos</msgid>
            <msgstr locale="ru_RU">Все фотографии</msgstr>
        </locale>
        <locale>
            <msgid>Information</msgid>
            <msgstr locale="ru_RU">Информация</msgstr>
        </locale>
        <locale>
            <msgid>Hub</msgid>
            <msgstr locale="ru_RU">Хаб</msgstr>
        </locale>
        <locale>
            <msgid>Desktop version</msgid>
            <msgstr locale="ru_RU">Полная версия</msgstr>
        </locale>
    </locales>
</theme>

=== webasyst/webasyst-framework/wa-apps/site/themes/vk/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="vk" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.1.29">
    <name locale="en_US">VK</name>
    <name locale="ru_RU">Вконтакте</name>
    <description locale="ru_RU">Ваш сайт во «Вконтакте» в виде Iframe-приложения.</description>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of the VK theme family</description>
            <description locale="ru_RU">Основной макет тем дизайна семейства VK</description>
        </file>
        <file path="vk.css" custom="0">
            <description locale="en_US">Core CSS of the VK theme family</description>
            <description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна VK</description>
        </file>
        <file path="vk.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout for the Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Internal app search form</description>
            <description locale="ru_RU">Форма поиска в приложении</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">My profile navigation</description>
            <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
<p><b>VK</b> design themes are designed for embedding Webasyst-powered websites into <a href="http://vk.com">VK.com</a> social network as iframe apps. VK theme family is universal — there is a theme for every basic Webasyst app: Site, Blog, Photos, Shop-Script, etc. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the VK (i.e. this) theme for the Site application. All VK design themes for other apps (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
<p>Темы <b>VK</b> разработаны для внедрения сайтов, созданных на основе фреймворка Вебасист, в соцсеть «<a href="http://vk.com">Вконтакте</a>» в виде iframe-приложений. Семейство тем VK универсальное — подходит для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема для приложения «Сайт» (данная тема). Все темы VK для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
]]>
    </about>
    <settings>
        <setting var="vk_app_id" control_type="text">
            <value>YOUR_VK_APP_ID</value>
            <name locale="en_US">VK App ID</name>
            <name locale="ru_RU">ID приложения «Вконтакте»</name>
            <description locale="en_US"></description>
            <description locale="ru_RU"><![CDATA[Для встраивания сайта в соцсеть в виде приложения необходимо создать приложение для «Вконтакте». Инструкция: <a href="http://www.webasyst.ru/help/27/shop-script-5-vkontakte-online-store/" target="_blank">http://www.webasyst.ru/help/27/shop-script-5-vkontakte-online-store/</a>]]></description>
        </setting>
        <setting var="vk_app_secret" control_type="text">
            <value>YOUR_VK_APP_SECRET</value>
            <name locale="en_US">VK App Secret</name>
            <name locale="ru_RU">Защищенный ключ приложения «Вконтакте»</name>
            <description locale="en_US"></description>
            <description locale="ru_RU"><![CDATA[Для встраивания сайта в соцсеть в виде приложения необходимо создать приложение для «Вконтакте». Инструкция: <a href="http://www.webasyst.ru/help/27/shop-script-5-vkontakte-online-store/" target="_blank">http://www.webasyst.ru/help/27/shop-script-5-vkontakte-online-store/</a>]]></description>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
    </settings>
</theme>
