=== webasyst/webasyst-framework/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Theme -->
<!ELEMENT theme (name+,description*,instruction*,support*,files*,about*, settings?, thumbs?, locales?, requirements?)>
<!ATTLIST theme
    id CDATA #REQUIRED
    system (1|0) "0"
    vendor CDATA #IMPLIED
    author CDATA #IMPLIED
    app CDATA #REQUIRED
    parent_theme_id CDATA #IMPLIED
    version CDATA #IMPLIED
    edition CDATA #IMPLIED
    source_theme_id CDATA #IMPLIED
    demo (1|0) "0"
>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    locale CDATA #REQUIRED
>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
    locale CDATA #REQUIRED
>

<!ELEMENT instruction (#PCDATA)>
<!ATTLIST instruction
    locale CDATA #REQUIRED
>

<!ELEMENT support (#PCDATA)>
<!ATTLIST support
    locale CDATA #REQUIRED
>

<!-- Theme's files list available for editing -->
<!ELEMENT files (file+)>

<!ELEMENT file (description*)>
<!ATTLIST file
    path CDATA #REQUIRED
    custom (1|0) "0"
    parent (1|0) "0"
    modified (1|0) "0"
>

<!-- Theme usage hints and instructions -->
<!ELEMENT about (#PCDATA)>
<!ATTLIST about
    locale CDATA #REQUIRED
>

<!-- Theme settings -->
<!ELEMENT settings (setting+)>
<!-- Theme setting -->
<!ELEMENT setting (value+,filename?,name+,tooltip*,description*,options?)>
<!ATTLIST setting
    var CDATA #REQUIRED
    control_type (text|select|checkbox|radio|color|color_select|image|image_select|image_width|paragraph|group_divider) "text"
    invisible (true|false) "false"
    icon_class CDATA #IMPLIED
    image CDATA #IMPLIED
    max_width CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
    locale CDATA #IMPLIED
>
<!ELEMENT tooltip (#PCDATA)>
<!ATTLIST tooltip
    locale CDATA #REQUIRED
>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT options (option+)>
<!ELEMENT option (name*,description*)>
<!ATTLIST option
    value CDATA #IMPLIED
>
<!--List of allowed thumb sizes-->
<!ELEMENT thumbs (thumb*)>
<!ELEMENT thumb (#PCDATA)>

<!--Theme strings-->
<!ELEMENT locales (locale+)>
<!ELEMENT locale (msgid,msgstr+)>
<!ELEMENT msgid (#PCDATA)>
<!ELEMENT msgstr (#PCDATA)>
<!ATTLIST msgstr
    locale CDATA #REQUIRED
>

<!--Theme requirements-->
<!ELEMENT requirements (requirement+)>
<!ELEMENT requirement (name*,description*)>
<!ATTLIST requirement
    property CDATA #REQUIRED
    value CDATA #REQUIRED
    strict (true|false) "false"
>

=== webasyst/webasyst-framework/wa-apps/photos/themes/default/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="default" system="0" vendor="webasyst" author="Webasyst" app="photos" parent_theme_id="site:default" version="4.0.0">
    <name locale="en_US">Default 4.0</name>
    <name locale="ru_RU">Дефолт 4.0</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="index.html" parent="1">
        </file>
        <file path="default.css" parent="1">
        </file>
        <file path="default.photos.css">
        </file>
        <file path="default.photos.js">
        </file>
        <file path="head.html">
            <description locale="en_US">Photos app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Фото»</description>
        </file>
        <file path="header.html">
            <description locale="en_US">App specific header content</description>
            <description locale="ru_RU">Содержимое «шапки» приложения</description>
        </file>
        <file path="main.html">
            <description locale="en_US">Main layout and navigation for the Photos app content</description>
            <description locale="ru_RU">Основной макет вывода содержимого и навигации в приложении «Фото»</description>
        </file>
        <file path="footer.html">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="photos-thumbs.html">
            <description locale="en_US">Photo list thumbnails view</description>
            <description locale="ru_RU">Список фотографий эскизами</description>
        </file>
        <file path="photos-plain.html">
            <description locale="en_US">Photo list plain view</description>
            <description locale="ru_RU">Список фотографий «простыней»</description>
        </file>
        <file path="photo.html">
            <description locale="en_US">One photo and its details</description>
            <description locale="ru_RU">Просмотр фотографий по одной</description>
        </file>
        <file path="home.html">
            <description locale="en_US">Wrapper for the main photo gallery homepage</description>
            <description locale="ru_RU">Обертка для главной страницы фотогалереи</description>
        </file>
        <file path="album.html">
            <description locale="en_US">Wrapper for photo album</description>
            <description locale="ru_RU">Обертка для альбома фотографий</description>
        </file>
        <file path="search.html">
            <description locale="en_US">Wrapper for photo search (filtering) results, e.g. by tag or by rating</description>
            <description locale="ru_RU">Обертка для страницы поиска (фильтрации) фотографий, например, по тегу или автору</description>
        </file>
        <file path="page.html">
            <description locale="en_US">Static page content</description>
            <description locale="ru_RU">Содержимое информационной страницы</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
        <file path="default.js" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Default</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Default theme for the Site application. All Default design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
<p>Default design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p><b>Default</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Default для приложения «Сайт» (данная тема). Все темы дизайна Default для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Default оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
    <thumbs>
        <thumb>200x0</thumb>
        <thumb>970x0</thumb>
    </thumbs>
</theme>

=== webasyst/webasyst-framework/wa-content/xml/example/wa-app-theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd" >
<theme id="my-theme" system="0" vendor="webasyst" author="Webasyst" app="my-app" version="1.0.0">
	<name locale="en_US"><![CDATA[Theme name]]></name>
	<name locale="ru_RU"><![CDATA[Название темы]]></name>
	<description locale="en_US"><![CDATA[Theme name description]]></description>
	<description locale="ru_RU"><![CDATA[Описание "название темы"]]></description>
	<files>
		<file path="index.html" custom="0">
			<description locale="en_US"><![CDATA[Primary file]]></description>
			<description locale="ru_RU"><![CDATA[Основной файл]]></description>
		</file>
	</files>
</theme>

=== webasyst/webasyst-framework/wa-apps/site/themes/nifty/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="nifty" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.2.17">
    <name locale="en_US">Nifty</name>
    <name locale="ru_RU">Nifty</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of the Nifty theme family</description>
            <description locale="ru_RU">Основной макет тем дизайна семейства Nifty</description>
        </file>
        <file path="nifty.css" custom="0">
            <description locale="en_US">Core CSS of the Nifty theme family</description>
            <description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна Nifty</description>
        </file>
        <file path="nifty.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout for the Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">My profile navigation</description>
            <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="navigation.html" custom="0">
            <description locale="en_US">Internal storefront navigation</description>
            <description locale="ru_RU">Внутренняя навигация по витрине магазина</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
<p><b>Nifty</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Nifty (i.e. this) theme for the Site application. All Nifty design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
<p>Nifty design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
<p><b>Nifty</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Nifty для приложения «Сайт» (данная тема). Все темы дизайна Nifty для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Nifty оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
    <settings>
        <setting var="color_scheme" control_type="select">
            <value>purple</value>
            <name locale="ru_RU">Цветовая гамма</name>
            <name locale="en_US">Color scheme</name>
            <options>
                <option value="purple">
                    <name locale="ru_RU">Фиолетовая</name>
                    <name locale="en_US">Purple</name>
                </option>
                <option value="green">
                    <name locale="ru_RU">Зеленая</name>
                    <name locale="en_US">Green</name>
                </option>
                <option value="blue">
                    <name locale="ru_RU">Синяя</name>
                    <name locale="en_US">Blue</name>
                </option>
                <option value="red">
                    <name locale="ru_RU">Красная</name>
                    <name locale="en_US">Red</name>
                </option>
                <option value="yellow">
                    <name locale="ru_RU">Желтая</name>
                    <name locale="en_US">Yellow</name>
                </option>
                <option value="white">
                    <name locale="ru_RU">Белая</name>
                    <name locale="en_US">White</name>
                </option>
                <option value="black">
                    <name locale="ru_RU">Черная</name>
                    <name locale="en_US">Black</name>
                </option>
            </options>
        </setting>
        <setting var="facebook_url" control_type="text">
            <value>#</value>
            <name locale="en_US">Facebook Page URL</name>
            <name locale="ru_RU">Адрес страницы в Фейсбуке</name>
        </setting>
        <setting var="twitter_url" control_type="text">
            <value>#</value>
            <name locale="en_US">Twitter URL</name>
            <name locale="ru_RU">Адрес страницы на Твиттере</name>
        </setting>
        <setting var="ajax_filters" control_type="checkbox">
            <value>1</value>
            <name locale="en_US">AJAX-enabled product by-feature filtering</name>
            <name locale="ru_RU">AJAX-фильтры товаров по характеристикам</name>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
        <setting var="use_shop_schedule" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать график работы магазина на текущую неделю из настроек Shop-Script</name>
            <name locale="en_US">Show online store’s working schedule for current week from Shop-Script settings</name>
            <description locale="ru_RU">При включении игнорируется настройка «Сокращенный график работы».</description>
            <description locale="en_US">When enabled, “Brief working schedule” setting is ignored.</description>
        </setting>
        <setting var="manual_schedule" control_type="text">
            <value></value>
            <name locale="ru_RU">Сокращенный график работы</name>
            <name locale="en_US">Brief working schedule</name>
            <description locale="ru_RU">Например: Пн—Сб 08:00–18:00</description>
            <description locale="en_US">Example: Mo—Sa 08:00–18:00</description>
        </setting>
    </settings>
</theme>

=== webasyst/webasyst-framework/wa-apps/blog/themes/default/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="default" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:default" version="26.1">
    <name locale="en_US">Webasyst 2026</name>
    <name locale="ru_RU">Webasyst 2026</name>
    <files>
        <file path="index.html" parent="1">
        </file>
        <file path="default.css" parent="1">
        </file>
        <file path="default.blog.js">
        </file>
        <file path="default.blog.css">
        </file>
        <file path="head.html">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="header.html">
            <description locale="en_US">App specific header content</description>
            <description locale="ru_RU">Содержимое «шапки» приложения</description>
        </file>
        <file path="banner.html">
            <description locale="en_US">App specific banner content</description>
            <description locale="ru_RU">Контент в области баннера</description>
        </file>
        <file path="main.html">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основной макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="footer.html">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="stream.html">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="post.album.html">
            <description locale="en_US">Photo album attached to the blog post</description>
            <description locale="ru_RU">Фотоальбом, прикрепленный к записи в блоге</description>
        </file>
        <file path="page.html">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
        <file path="default.js" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Default</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Default theme for the Site application. All Default design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
<p>Default design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p><b>Default</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Default для приложения «Сайт» (данная тема). Все темы дизайна Default для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Default оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
</theme>

=== webasyst/webasyst-framework/wa-apps/blog/themes/facebook/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="facebook" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:facebook" version="1.1.3">
    <name locale="en_US">Facebook</name>
    <name locale="ru_RU">Facebook</name>
    <files>
        <file path="facebook.blog.css" custom="0">
            <description locale="en_US">Core Blog app CSS</description>
            <description locale="ru_RU">Основной CSS приложения «Блог»</description>
        </file>      
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
        <file path="navigation.html" custom="0">
            <description locale="en_US">Internal app navigation</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Internal app search form</description>
            <description locale="ru_RU">Форма поиска в приложении</description>
        </file>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="facebook.css" custom="0" parent="1">
        </file>
        <file path="facebook.js" custom="0" parent="1">
        </file>
        <file path="facebook.blog.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Facebook</b> design themes are designed for embedding Webasyst-powered websites into <a href="http://www.facebook.com">Facebook</a> social network as iframe apps. Facebook theme family is universal — there is a theme for every basic Webasyst app: Site, Blog, Photos, Shop-Script, etc. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Facebook theme for the Site application. All Facebook design themes for other apps (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p>Темы <b>Facebook</b> разработаны для внедрения сайтов, созданных на основе фреймворка Вебасист, в «<a href="http://www.facebook.com">Фейсбук</a>» в виде iframe-приложений. Семейство тем Facebook универсальное — подходит для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема для приложения «Сайт». Все темы Facebook для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
]]>
    </about>    
</theme>
